### ISSUE TITLE
APRRES - to be released public project

### ISSUE THREAD

**Issue by xssfox** [aprsorg/aprs-deviceid#156]
```yml
 - tocall: APRRES
   vendor: xssfox
   model: APRS-RepeaterRescue
   class: network
   os: embedded
   contact: repeater-rescue@michaela.lgbt
   features:
      - messaging
```
