### ISSUE TITLE
New APRS TOCALL Request: APLDAG EA2CQ APRS & LoRa Spotting Service

### ISSUE THREAD

**Issue by EA2CW** [aprsorg/aprs-deviceid#157]
Hello, 
We would want to request the TOCALL "APLDAG" for "DAGA", a spotting service from talkies and LoRa trackers to SOTA (Summits On The Air) sotawatch service.
It is at final stages of development by Iñigo EA2CQ and myself from an idea of Jose EA2EYI. 
The data:

tocall: APLDAG
vendor: Inigo, EA2CQ
model: DAGA LoRa/APRS SOTA spotting
class: service
os:Linux
service: APRS message bot
contact: ea2cq@irratia.org
features: messaging

Thank you & 73
Mikel EA2CW | AE2CW

**Comment by hessu** [comment]
Hi!

Thanks, I'm making the allocation as follows. Removed the "service" field because there is no such field, and removed the "os" field as it's a service which nobody else will be running; it doesn't make much sense to announce the OS it'll be running on.

```
 - tocall: APLDAG
   vendor: Inigo, EA2CQ
   model: DAGA LoRa/APRS SOTA spotting
   class: service
   contact: ea2cq@irratia.org
   features:
     - messaging

```
