### ISSUE TITLE
Requesting a TOCALL for aprs-weather-submit

### ISSUE THREAD

**Issue by rhymeswithmogul** [aprsorg/aprs-deviceid#192]
Hello, everyone!  I'm the author of [`aprs-weather-submit`](https://github.com/rhymeswithmogul/aprs-weather-submit).  This free and open-source app allows amateurs to submit weather data at will through a command-line interface, or it can be called automatically by a script or other daemon as a building block to create your own APRS-IS-capable weather station!

I'd like to register a TOCALL for it:

```yaml
- tocall: APRSWX
  vendor: Colin Cogle, W1DNS
  model: aprs-weather-submit
  class: software
  os: Multiple
  contact: https://github.com/rhymeswithmogul/aprs-weather-submit/
```

If the `APRS??` prefix is reserved, I don't mind thinking of something else.

Also, does the contact field _need_ to be an email address?  I'd prefer it link to my GitHub project page where I can collect and triage bug reports and discussions.  If not, I have no problem submitting my email address.
