### ISSUE TITLE
Add Mobilinkd TNCs

### ISSUE THREAD

**Issue by mobilinkd** [aprsorg/aprs-deviceid#202]
```yaml  
 - tocall: APMBL?
   vendor: Mobilinkd LLC
   model: various
   class: network
   os: embedded
   contact: support@mobilinkd.com

 - tocall: APMBL3
   vendor: Mobilinkd LLC
   model: TNC3
   class: network
   os: embedded
   contact: support@mobilinkd.com

 - tocall: APMBL4
   vendor: Mobilinkd LLC
   model: TNC4
   class: network
   os: embedded
   contact: support@mobilinkd.com

 - tocall: APMBLN
   vendor: Mobilinkd LLC
   model: NucleoTNC
   class: network
   os: embedded
   contact: support@mobilinkd.com
```
Requesting a 5-letter prefix, plus individual model designators for upcoming digi firmware releases.
