### ISSUE TITLE
Proposed TOCALL allocation

### ISSUE THREAD

**Issue by W0CHP** [aprsorg/aprs-deviceid#62]
I am proposing that the popular [WeeWX weather software](https://github.com/weewx/weewx) has a TOCALL allocation:

```yaml
- tocall: APWX??
  vendor: Tom Keffer and Matthew Wall
  model: WeeWX Weather Software
  class: software
  os: Linux/Unix
```

The goal is to replace the existing TOCALL packet preamble in WeeWX from `APRS` to `APWX??`:
https://github.com/weewx/weewx/blob/7024f046cffcff145af4e195cefc18f9c08cd3fb/bin/weewx/restx.py#L1231
