### ISSUE TITLE
Tocall and mic-e identifier allocation for Kenwood D75

### ISSUE THREAD

**Issue by hessu** [aprsorg/aprs-deviceid#78]
JVCKenwood has privately requested the allocation of tocall and mic-e identifiers for the Kenwood D75.

```
 - prefix: ">"
   suffix: "&"
   vendor: Kenwood
   model: TH-D75
   class: ht
   features:
     - messaging

 - tocall: APK005
   vendor: Kenwood
   model: TH-D75
   class: ht
```
