### ISSUE TITLE
Confused about ordering / preference on overlapping tocalls

### ISSUE THREAD

**Issue by xssfox** [aprsorg/aprs-deviceid#86]
The README.md suggests looking for the longest match however there are cases where you can have a tie based on how many characters match (see example below). I'm guessing that the idea is that we should favour the longest matching prefix first? so `APC???` would be the APRS device ID. Some clarification around this would be good.

What does APCAD match?
```yaml
 - tocall: APC???
   vendor: Rob Wittner, KZ5RW
   model: APRS/CE
   class: app
 - tocall: APnnnD
   vendor: Painter Engineering
   model: uSmartDigi D-Gate
   class: dstar
```
