### ISSUE TITLE
New TOCALL allocation for Lilygo T-Echo tracker firmware

### ISSUE THREAD

**Issue by cfr34k** [aprsorg/aprs-deviceid#94]
Hello!

My [APRS tracker firmware for the LilyGo T-Echo](https://github.com/cfr34k/t-echo-lora-aprs) has become reasonably mature and it would be nice to have a non-experimental ID for it. Could you allocate the following entry, please?

```yaml
 - tocall: APLETK
   vendor: DL5TKL
   model: DL5TKL’s T-Echo tracker firmware
   class: tracker
   os: embedded
   contact: cfr34k-git@tkolb.de
```

73 de Thomas DL5TKL
